### ISSUE TITLE
Bad timing checking en.relay.friendi.ca ?

### ISSUE THREAD

**Issue by realkinetix** [brodi1/activitypub-relays#1]
https://en.relay.friendi.ca/inbox

Howdy!

This should be running just fine.

Glad you're maintaining a list like this!

Thanks.

**Comment by brodi1** [comment]
Hi @realkinetix 

I added it back to the _active working relays_ section (https://github.com/brodi1/activitypub-relays/commit/f386e8be5bd42cc92e1b3ad95dccfa65f29f74a5)

Thanks for informing me! 👍 😄
