### ISSUE TITLE
Investigating https://neighbours.aus.social/ 

### ISSUE THREAD

**Issue by shleeable** [brodi1/activitypub-relays#10]
Hey, Any reason https://neighbours.aus.social/ is listed as not working? 

I'll fix it up if I can see the problem.

**Comment by asdfisdffdg** [comment]
maybe cuz it dont work bru

**Comment by shleeable** [comment]
nailed it.

**Comment by Volkor3-16** [comment]
Working for me fine :)
![firefox_A0g3jycVhc](https://user-images.githubusercontent.com/4054374/202656179-a1ead074-6a67-4083-9151-6963422ac5ad.png)

**Comment by quicoto** [comment]
Yep, just added it to my single-user instance. Works 💜 

I think you can just open a PR to move it to the working list :)

**Comment by shleeable** [comment]
Glad to hear it.
