### ISSUE TITLE
Move federation.stream to "relays that maybe? work" 

### ISSUE THREAD

**Issue by ThaMunsta** [brodi1/activitypub-relays#18]
Can't resolve DNS record. Might work again one day but doubtful since their last known contact (@federationstream@mstdn.social) is gone from that instance.
Sorry if this should have been a fork & PR.

**Comment by brodi1** [comment]
> Can't resolve DNS record

same here

> Might work again one day but doubtful since their last known contact

it could be....
> Sorry if this should have been a fork & PR.

np

@ThaMunsta thanks!
