### ISSUE TITLE
German Mastodon Relay 

### ISSUE THREAD

**Issue by b3nscher** [brodi1/activitypub-relays#32]
Hey, 

I am the admin of swapping.social, a German Mastodon instance. For this I have also created a relay for German instances. Could this be added to your list?

To ensure that only selected instances can connect, a join request is necessary. This can be done at admin@joinmastodon.de. 

The relay can be found at https://streamb0x.de

Kind regards 
Ben

**Comment by brodi1** [comment]
@b3nscher thanks Ben!
